bdmserver.file.location = (System.getenv('BDMSERVER_FILE_LOCATION') ?: '/tmp/upload')
bdmserver.AXWebServicesUrl = (System.getenv('BDMSERVER_AXWEBSERVICEURL') ?: 'http://axserver/appxtender/axservicesinterface.asmx')
bdmserver.AXWebAccessURL = (System.getenv('BDMSERVER_AXWEBACCESSURL') ?: 'http://axserver/appxtender/')
bdmserver.Username = (System.getenv('BDMSERVER_USERNAME') ?: 'BDMAPI_SUPERUSER')
bdmserver.DataSource = (System.getenv('BDMSERVER_DATASOURCE') ?: 'TEST')
bdmserver.BdmDataSource = (System.getenv('BDMSERVER_BDMDATASOURCE') ?: 'TEST')