bannerdb.jdbc=jdbc:oracle:thin:@//zdevl.db.usu.edu:1521/zdevl
banproxy.username=banproxy
banproxy.initialsize=25
banproxy.maxtotal=400
banproxy.maxidle=-1
banproxy.maxwait=30000
banssuser.username=ban_ss_user
banssuser.initialsize=25
banssuser.maxtotal=400
banssuser.maxidle=-1
banssuser.maxwait=30000
banner9.baseurl=https://ss-zdevl.banner.usu.edu
remove.abandoned.on.maintenance=true
remove.abandoned.on.borrow=true
remove.abandoned.timeout=2100
remove.ss.abandoned.timeout=60
log.abandoned=true
bannerdb.rowPrefetch=150
