---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssb-registration
  namespace: zdevl
spec:
  replicas: 1
  selector:
    matchLabels:
      edu.usu.banner.zdevl/in-maintenance: 'no'
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: ssb-registration
          image: usuit/banner9-ssb-registration:9.40.1-zdevl
          imagePullPolicy: IfNotPresent
