server {
    listen       80;
    server_name  localhost;

    #access_log  /var/log/nginx/host.access.log  main;

    location = /health {
        # Health check
        access_log off;
        add_header 'Content-Type' 'application/json';
        return 200 '{"status": "UP"}';
    }

    location = /redirect-offline {
        access_log off;
        return 302 https://usu.service-now.com/aggies?id=kb_article_view&sysparm_article=KB0015737;
    }

    location / {
        root   /usr/share/nginx/html;
    }

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    error_page   400 401 402 403 404 /redirect-landing;
    location = /redirect-landing {
        return 302 https://it.usu.edu/banner/development;
    }
}


